version: '3'
services:
  express:
    build: node-express/
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://cache
  graphql:
    build: node-graphql/
    ports:
      - "4000:4000"
  redis:
    image: redis:latest
    container_name: cache
    expose:
      - 6379